### ISSUE TITLE
Git tag newest releases

### ISSUE THREAD

**Issue by emanuelb** [fsw/coffee.wallet#78]
Latest version of android app in google play-store is: "0.17.3" from "June 3, 2021"
https://play.google.com/store/apps/details?id=coffee.software.coffeewallet

while the latest tag is: 0.16.1 from "May 13"
https://github.com/coffee-software/coffee.wallet/tags

Please tag the newest version currently available for download & ensure in future tag is created before releasing new version.

**Comment by fsw** [comment]
Hi. Thanks for noticing it. 
Indeed tags were created but not pushed to repo. 
All should be properly tagged now.

**Comment by emanuelb** [comment]
latest tag is 0.21.0 from Jun 22 https://github.com/coffee-software/coffee.wallet/tags
while version on google play 0.22 Updated on Jul 13, 2022
https://play.google.com/store/apps/details?id=coffee.software.coffeewallet

**Comment by fsw** [comment]
@emanuelb fixed. I've added tags push to deploy scripts so this wont be missed again.
