### ISSUE TITLE
Publish content of coffee.wallet.priv directory or create it in browserify.sh script

### ISSUE THREAD

**Issue by emanuelb** [fsw/coffee.wallet#88]
The only mention of `coffee.wallet.priv` directory is in:
https://github.com/coffee-software/coffee.wallet/blob/1321967c521a3e7f0be7eb05ba0876a03e751a3d/browserify.sh#L38-L44

running `./browserify.sh` will result in errors:
```
quick mode
./browserify.sh: line 29: ../coffee.wallet.priv/website/engine.js: No such file or directory
mv: cannot stat '../coffee.wallet.priv/website/engine.js': No such file or directory
```

cause `>` cant write to a folder that doesn't exists, there is no `website` and `coffee.wallet.priv` directories in this repo.

a workaround is to run command `mkdir -p ../coffee.wallet.priv/website` which can be added to the `./browserify.sh` script as well in case the folder content is not needed.

**Comment by fsw** [comment]
@emanuelb thanks for this report.

This part of the script was compiling raw engine that is later available at https://wallet.coffee/engine.min.js for our online tools like "Paper Wallets Generator" https://wallet.coffee/paper-wallets-generator.html

This should not be here as it is not used by the application. I have removed this part from develop.
