### ISSUE TITLE
License is not open source due to modification restrictions but open source claims in many places

### ISSUE THREAD

**Issue by emanuelb** [fsw/coffee.wallet#94]
The license used in:
https://github.com/coffee-software/coffee.wallet/blob/develop/LICENSE.txt

is not open source (OSI approved license) https://opensource.org/licenses/ as open source also mean the right to modify

From open source definition : https://opensource.org/osd/

> 3. Derived Works
The license must allow modifications and derived works, and must allow them to be distributed under the same terms as the license of the original software.

Publishing the source code make it source available (also called shared source) but it's not enough to be open source.

While from LICENSE.txt:

https://github.com/coffee-software/coffee.wallet/blob/aae2e9ce1c8548795dd30a63eda94571ccdeb874/LICENSE.txt#L12-L14

places app claimed to be open source:

1. on website at: https://wallet.coffee/#open
2. in README.md at: https://github.com/coffee-software/coffee.wallet/blob/a987d31525bbe1feb245c22f719e8c702b4de852/README.md#L3

Fix:

1. Use known open source license, list to choose from: https://opensource.org/licenses/
2. in case not open source license is used, don't use the term Open Source but use another term instead.

**Comment by fsw** [comment]
Hi @emanuelb, thanks for feedback.

Yes I did not use this term as OSI approves it.
I used it to highlight the most important aspect of it from a wallet user perspective ie knowing what your software is doing (source is available).

Initial, custom license allowed this but I was always considering changing it to OSI compliant license, so I guess this will be a good moment considering your question so I have released Coffee Wallet under GPLv3 just now:

https://github.com/coffee-software/coffee.wallet/pull/95

cheers
